// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxsbibzpcwzlzigxantp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4c2JpYnpwY3d6bHppZ3hhbnRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNTIzNDYsImV4cCI6MjA2ODYyODM0Nn0.EK0kfBoeXCVVy9kEzkQqGNwaEznICeSK3KdhCzuZbE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});